fastlane_version '2.157'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :tests do
        run_tests(
            devices: ["iPhone 14 Pro"],
            scheme: "cloudkit-client-unittests",
            code_coverage: true
        )
        slather(
            cobertura_xml: true,
            scheme: "cloudkit-client-unittests",
            proj: "cloudkit-client.xcodeproj",
            verbose: true,
            output_directory: "slather_output"
        )
    end
end
